### PR TITLE
Copy SVG utilities from cs61a-apps

### PR DESCRIPTION
**Pull request by rahularya50**
Copied from https://github.com/Cal-CS-61A-Staff/cs61a-apps/blob/master/gui_files/svg.py and https://github.com/Cal-CS-61A-Staff/cs61a-apps/blob/master/gui_files/svg_test.py, both under MIT license.

Checks pass with `make check`, verified that `svg_test.py` is actually being run.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #10
* #9
* #8
* __->__ #1

### CODE REVIEW

**Comment by tylerhou** [comment]
Add instructions on how to use in README.md?

**Comment by rahularya50** [comment]
> Add instructions on how to use in README.md?

Next diffs in stack? This diff just copies over code from elsewhere, I want to separate them out so it's easier to review the new code.

**Comment by tylerhou** [comment]
I don't see the other diffs in the stack. Also, do you think this code belongs in the `python` folder? Maybe a `tools` folder would be more appropriate. Unless you think they might call this code from inside Python.

**Comment by rahularya50** [comment]
> I don't see the other diffs in the stack. Also, do you think this code belongs in the python folder? Maybe a tools folder would be more appropriate. Unless you think they might call this code from inside Python.

Sorry, sorted out my stack (sorry also for the random closed PRs lol). I think they could call this code via the `visualize_as_svg` method on the `Instance` / `Solution` classes, yep.

**Review by tylerhou — APPROVED** [review]

**Pull request merged**
